# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CometChatSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CometChatSwift
   pod 'CometChatUIKitSwift', '4.0.3'
  pod 'CometChatCallsSDK', '4.0.1'

end

target 'CometChat KitchenSink UITests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CometChatSwift
   pod 'CometChatUIKitSwift', '4.0.3'
  pod 'CometChatCallsSDK', '4.0.1'

end

target 'CometChat KitchenSinkTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CometChatSwift
   pod 'CometChatUIKitSwift', '4.0.3'
  pod 'CometChatCallsSDK', '4.0.1'

end
