# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'CometChatSwift' do
  pod 'CometChatPro', '2.4.2'
  pod 'CometChatCalls', '2.1.1'
 

end

target 'CometChat KitchenSinkTests' do
   pod 'CometChatPro', '2.4.2'
   pod 'CometChatCalls', '2.1.1'

end

target 'CometChat KitchenSink UITests' do
   pod 'CometChatPro', '2.4.2'
   pod 'CometChatCalls', '2.1.1'

end
