# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CometChatPro-swift-sampleApp' do
  pod 'CometChatPro', '1.8.12-Xcode11'
    pod 'SDWebImage', '~> 4.0'
end

target 'CometChatPro-swift-sampleAppTests' do
  
  pod 'CometChatPro', '1.8.12-Xcode11'
   pod 'SDWebImage', '~> 4.0'
end
