

target 'CometChatPro-swift-sampleApp' do
 
    pod 'CometChatPro', '2.0.4'
    pod 'SDWebImage', '~> 4.0'
end

target 'CometChatPro-swift-sampleAppTests' do
  
   pod 'CometChatPro', '2.0.4'
   pod 'SDWebImage', '~> 4.0'
end
